version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: my_app_store-deluge_server_1
      APP_PORT: 8112

  server:
    image: lscr.io/linuxserver/deluge:2.1.1@sha256:580afe15815aac87301d84ddcf97dc45aa89f5fd4b548c943534373dd8ae96b0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: on-failure
